-- LOJA TETELESTAI 2026
-- Execute este arquivo completo no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.loja_configuracoes (
  id uuid primary key default gen_random_uuid(),
  chave text not null unique default 'tetelestai-2026',
  nome_loja text not null default 'Loja Tetelestai',
  loja_ativa boolean not null default false,
  mostrar_botao_topo boolean not null default false,
  texto_botao_topo text not null default 'PEÇA AGORA SUA CAMISETA',
  titulo_vitrine text not null default 'Camisetas Tetelestai 2026',
  descricao_vitrine text,
  banner_url text,
  vendas_inicio timestamptz,
  vendas_fim timestamptz,
  retirada_data date,
  retirada_inicio time,
  retirada_fim time,
  retirada_local text default 'Av. Ver. José Donato, 913 — Cabreúva/SP',
  retirada_instrucoes text,
  aceitar_pix boolean not null default true,
  aceitar_cartao boolean not null default true,
  aceitar_retirada boolean not null default true,
  whatsapp_ativo boolean not null default false,
  exigir_confirmacao_medidas boolean not null default true,
  mensagem_loja_fechada text not null default 'A coleção está sendo preparada. Em breve, as vendas estarão disponíveis.',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.loja_clientes (
  id uuid primary key default gen_random_uuid(),
  nome_completo text not null,
  celular text not null unique,
  email text not null,
  origem text not null default 'site' check (origem in ('site','whatsapp','manual')),
  whatsapp_opt_in boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.loja_produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  slug text not null unique,
  descricao text,
  imagem_principal_url text,
  preco numeric(12,2) not null default 0 check (preco >= 0),
  publicado boolean not null default false,
  destaque boolean not null default false,
  controlar_estoque boolean not null default false,
  ordem integer not null default 0,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.loja_produto_imagens (
  id uuid primary key default gen_random_uuid(),
  produto_id uuid not null references public.loja_produtos(id) on delete cascade,
  url text not null,
  texto_alternativo text,
  ordem integer not null default 0,
  criado_em timestamptz not null default now()
);

create table if not exists public.loja_variacoes (
  id uuid primary key default gen_random_uuid(),
  produto_id uuid not null references public.loja_produtos(id) on delete cascade,
  modelo text not null,
  publico text,
  aviso_modelagem text,
  tamanho text not null,
  comprimento_cm numeric(6,2),
  largura_cm numeric(6,2),
  preco_adicional numeric(12,2) not null default 0,
  estoque integer check (estoque is null or estoque >= 0),
  ativa boolean not null default true,
  ordem integer not null default 0,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique(produto_id, modelo, tamanho)
);

create table if not exists public.loja_pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null references public.loja_clientes(id),
  origem text not null default 'site' check (origem in ('site','whatsapp','manual')),
  status text not null default 'aguardando_pagamento' check (status in ('rascunho','aguardando_pagamento','pago','pagamento_na_retirada','em_separacao','pronto_retirada','retirado','cancelado')),
  forma_pagamento text check (forma_pagamento in ('pix','cartao','retirada')),
  status_pagamento text not null default 'pendente' check (status_pagamento in ('pendente','processando','aprovado','recusado','cancelado','estornado','na_retirada')),
  subtotal numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  confirmou_medidas boolean not null default false,
  observacoes_cliente text,
  observacoes_internas text,
  pagamento_provedor text,
  pagamento_referencia text,
  pagamento_url text,
  pago_em timestamptz,
  retirado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.loja_pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.loja_pedidos(id) on delete cascade,
  produto_id uuid references public.loja_produtos(id) on delete set null,
  variacao_id uuid references public.loja_variacoes(id) on delete set null,
  produto_nome text not null,
  modelo text not null,
  publico text,
  tamanho text not null,
  comprimento_cm numeric(6,2),
  largura_cm numeric(6,2),
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  valor_total numeric(12,2) not null check (valor_total >= 0),
  criado_em timestamptz not null default now()
);

create table if not exists public.loja_pedido_historico (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.loja_pedidos(id) on delete cascade,
  status_anterior text,
  status_novo text not null,
  descricao text,
  alterado_por text,
  criado_em timestamptz not null default now()
);

create index if not exists idx_loja_produtos_publicado on public.loja_produtos(publicado, ordem);
create index if not exists idx_loja_variacoes_produto on public.loja_variacoes(produto_id, ativa);
create index if not exists idx_loja_pedidos_cliente on public.loja_pedidos(cliente_id);
create index if not exists idx_loja_pedidos_status on public.loja_pedidos(status, criado_em desc);
create index if not exists idx_loja_itens_pedido on public.loja_pedido_itens(pedido_id);

insert into public.loja_configuracoes (chave)
values ('tetelestai-2026')
on conflict (chave) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('loja-tetelestai', 'loja-tetelestai', true, 10485760, array['image/jpeg','image/png','image/webp','image/svg+xml'])
on conflict (id) do update set public = true;

-- O portal atual usa login próprio e não Supabase Auth. Por isso, as tabelas administrativas
-- permanecem sem RLS, seguindo o padrão existente do sistema. Antes de abrir o portal ao
-- público, migre o login para Supabase Auth e aplique políticas por função.
alter table public.loja_configuracoes disable row level security;
alter table public.loja_clientes disable row level security;
alter table public.loja_produtos disable row level security;
alter table public.loja_produto_imagens disable row level security;
alter table public.loja_variacoes disable row level security;
alter table public.loja_pedidos disable row level security;
alter table public.loja_pedido_itens disable row level security;
alter table public.loja_pedido_historico disable row level security;

drop policy if exists "Imagens publicas da loja" on storage.objects;
create policy "Imagens publicas da loja" on storage.objects for select
using (bucket_id = 'loja-tetelestai');

drop policy if exists "Upload imagens da loja" on storage.objects;
create policy "Upload imagens da loja" on storage.objects for insert
with check (bucket_id = 'loja-tetelestai');

drop policy if exists "Atualizar imagens da loja" on storage.objects;
create policy "Atualizar imagens da loja" on storage.objects for update
using (bucket_id = 'loja-tetelestai');

drop policy if exists "Excluir imagens da loja" on storage.objects;
create policy "Excluir imagens da loja" on storage.objects for delete
using (bucket_id = 'loja-tetelestai');
