name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Conferir versões
        run: |
          node -v
          java -version
          echo $JAVA_HOME

      - name: Instalar dependências
        run: npm install

      - name: Build React
        run: npm run build

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Forçar Java 21 no Gradle
        run: echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties

      - name: Permissão Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK Release
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Salvar APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ADJACARE-APK-RELEASE
          path: android/app/build/outputs/apk/release/app-release.apk